---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
    - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "lib/**/*.rb"
