---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
    # Parameter definitions of `interface` and `ppd` are very similar by nature
    - aa989b647783355298a7fe43a93ce9a2
    exclude_paths:
    - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "lib/**/*.rb"
