---
AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
Layout/IndentHeredoc:
  Enabled: false
Lint/BooleanSymbol:
  Enabled: false
Metrics/LineLength:
  Max: 144
  AllowURI: true
  URISchemes:
    - http
    - https
    - ipp
    - ipps
    - lpd
    - socket
    - puppet
Metrics/BlockLength:
  Enabled: false
