---
AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 144
  AllowURI: true
  URISchemes:
    - http
    - https
    - ipp
    - ipps
    - lpd
    - socket
    - puppet
Metrics/BlockLength:
  Enabled: false
