---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
Layout/IndentHeredoc:
  Enabled: false
Lint/BooleanSymbol:
  Enabled: false
Metrics/LineLength:
  Max: 144
  AllowURI: true
  URISchemes:
    - http
    - https
    - ipp
    - ipps
    - lpd
    - socket
    - puppet
  Exclude:
    - 'spec/classes/init_spec.rb'
Metrics/BlockLength:
  Enabled: false
Naming/PredicateName:
  Exclude:
    - 'lib/puppet/type/cups_queue.rb'
Performance/RegexpMatch:
  Enabled: false
Style/AccessModifierDeclarations:
  Exclude:
    - 'lib/puppet/provider/cups_queue/cups.rb'
    - 'lib/puppet/type/cups_queue.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
