---
sudo: false
language: ruby
cache: bundler
bundler_args: --without acceptance_testing metatools
env:
- PUPPET_GEM_VERSION='~> 6.0'
- PUPPET_GEM_VERSION='~> 5.0'
rvm:
- 2.4.5
- 2.5.3
- 2.6.1
before_install:
- gem update --system
- gem install bundler
script: bundle exec rake travis:ci
jobs:
  include:
  - stage: Report test coverage to code climate
    if: branch = master
    rvm: 2.6.1
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    script:
    - bundle exec rake spec
    after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - stage: Release on Puppet Forge
    if: branch = release
    rvm: 2.6.1
    script: bundle exec rake travis:deploy?
    deploy:
      provider: puppetforge
      user: leoarnold
      password:
        secure: n9Ba1nVpdhMuM73rmX7qBR49HK7SXvhpVqNYT8MTgCTLYfpQ0m4U9Y6jL7KL2UsNVr4DBITpdN0gHOCKRqjwN3/zxs4Kh+NAWTWTho3hnDMEQXoMctOZ6qdyXC1PoR8bu7HLbK3ZspGLFzzKHMumCp3Nn35rnmW3FM67hM/Lg3jJTmTioHuoDnAkh5cwspUIRPEPWvZamht2Adtj6k8gmMhwXDp76vbivA8LZd4Z43lb2hPECzMaSSap+rTHvnc67W9AYgOMwNJJ4eAjJvXwUsyviVfwHpYfp+UiL3qg/HOC8CwrCgIEQ88tCW0llG06vD3FEDDLr+BWqEMFaOtmHY4FGMP6p+eIFgucWLAZVws13ekiFQ61529R1dJD/yOJNciCYczjHX/mO4yJ5CU7TM2zhE04xdt1DrCKB/ctmzWiZNUjgWVkE0h/jPaoG6vy7l77lpYkMP5XUpWoyc/VSqlnaBshhS3M/QWiiyUlGIYZJ0gwtnmI4zRxUbI+j7xTM2wkkb0e5eVBqB8VXnBlau6Fz4PUlqLgb4K/G46G5d/+hZlL2vovDJNCH1ak20NVRMOOdwnl1yZfEQpZ8bu9pz0HuAT1X8iIxk5OZIQCVphRr9ao5Pct6yQs+BLH8itFEX9U+r5VWeCntoz+SBllFogr+EvNk+9kZcv3RhD356w=
      skip_cleanup: true
      on:
        branch: release
  - stage: Release on GitHub
    if: branch = release
    rvm: 2.6.1
    script: bundle exec rake github:release
  - stage: Update GitHub Pages
    if: branch = release
    rvm: 2.6.1
    script: skip
    before_deploy: bundle exec rake github:pages
    deploy:
      provider: pages
      local-dir: doc
      github-token: $GITHUB_TOKEN
      keep-history: true
      skip_cleanup: true
      on:
        branch: release
