---
sudo: false
language: ruby
cache: bundler
bundler_args: --without acceptance_testing metatools
env:
- PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
rvm:
- 2.2.6
- 2.3.3
- 2.4.0
script: bundle exec rake static_checks
after_script: bundle exec codeclimate-test-reporter
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
