---
sudo: false
language: ruby
cache: bundler
bundler_args: --without acceptance_testing metatools
env:
- PUPPET_GEM_VERSION='~> 4.0'
- PUPPET_GEM_VERSION='5.0.0'
- PUPPET_GEM_VERSION='~> 5.0'
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
before_install:
- gem update --system
- gem update bundler
script: bundle exec rake travis:ci
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
