---
sudo: false
language: ruby
bundler_args: --without acceptance_testing
script:
- bundle exec rake release_checks
- bundle exec rake mdl
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
