---
sudo: false
language: ruby
before_install: gem update bundler --pre
# Travis CI does not detect `gems.rb` yet
# so we run bundler explicitly
install: bundle install --jobs=3 --retry=3 --without acceptance_testing metatools
cache: bundler
bundler_args: --without acceptance_testing metatools
env:
- PUPPET_GEM_VERSION='4.0.0' STRICT_VARIABLES='yes'
- PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
- PUPPET_GEM_VERSION='5.0.0'
- PUPPET_GEM_VERSION='~> 5.0'
rvm:
- 2.3.4
- 2.4.1
matrix:
  exclude:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION='4.0.0' STRICT_VARIABLES='yes'
script: bundle exec rake static_checks
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
