---
sudo: false
language: ruby
bundler_args: --without acceptance_testing metatools
script:
- bundle exec rake release_checks
- bundle exec rake mdl
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="4.0.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
