---
sudo: required
dist: trusty
services: docker
language: ruby
cache: bundler
bundler_args: --without $BUNDLE_WITHOUT
script: bundle exec rake $RAKE_TASK
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: RAKE_TASK='static_checks' BUNDLE_WITHOUT='acceptance_testing metatools' PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
  - rvm: 2.2.6
    env: RAKE_TASK='static_checks' BUNDLE_WITHOUT='acceptance_testing metatools' PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
  - rvm: 2.3.3
    env: RAKE_TASK='static_checks' BUNDLE_WITHOUT='acceptance_testing metatools' PUPPET_GEM_VERSION='~> 4.0' STRICT_VARIABLES='yes'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='centos-7-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='fedora-20-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='fedora-24-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='debian-7-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='debian-8-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='ubuntu-14.04-docker' BUNDLE_WITHOUT='metatools'
  - rvm: 2.3.3
    env: RAKE_TASK='beaker' BEAKER_set='ubuntu-16.04-docker' BUNDLE_WITHOUT='metatools'
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3402fe31d5b814c57316
    on_success: always
    on_failure: always
    on_start: never
